title: "BrainBoost Hub"
description: "Affordable nootropics and cognitive enhancers for students and creatives"
repository: mikael-ops/brainboost-hub
url: "https://mikael-ops.github.io"
baseurl: "/brainboost-hub"

# Theme
remote_theme: "mmistakes/minimal-mistakes"

# Plugins (all GitHub Pages–supported)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Site Author (you can customize more later)
author:
  name: "Your Name"
  bio: "Exploring productivity and affordable brain hacks."
  location: "Estonia"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mikael-ops"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true

  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
